### ISSUE TITLE
Pushing release assets to cdnjs or similar content delivery

### ISSUE THREAD

**Issue by tatut** [SWI-Prolog/npm-swipl-wasm#135]
It would be convenient to have the swipl-bundle.js in a CDN that is easily accessible, for cases where you want it cached and separate from your prolog .pl files.

For smaller apps, that are just an HTML file with Prolog code embedded in `script` tags.

**Comment by jeswr** [comment]
We use github pages to [achieve this in eye-js](https://github.com/eyereasoner/eye-js#browser-builds) we could do a similar thing here.

**Comment by jeswr** [comment]
#137 Should add this support - usage description is provided in the readme. All going well CI should pass and it should merge and release in the next couple hours. Let me know if everything is working for you then :)

**Comment by jeswr** [comment]
Re-opening this as a reminder to enable this github pages setting when #138 merges.
