### ISSUE TITLE
bug: `cross-fetch` is not a dependency

### ISSUE THREAD

**Issue by jeswr** [SWI-Prolog/npm-swipl-wasm#165]
It needs to be since it is part of the script (see https://swi-prolog.discourse.group/t/wiki-discussion-swi-prolog-in-the-browser-using-wasm/5651/163?u=jeswr)

**Comment by jeswr** [comment]
Perhaps we should just add depcheck at the same time

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/wiki-discussion-swi-prolog-in-the-browser-using-wasm/5651/165
