### ISSUE TITLE
Can't find swipl-generate

### ISSUE THREAD

**Issue by JanWielemaker** [SWI-Prolog/npm-swipl-wasm#207]
The docs says to use `swipl-generate ./max.pl ./dist/max.ts`, but I cannot find this script.   Cloned the repo and ran `yarn`,   As all the other generated stuff is there, I wonder where this script is ...

**Comment by jeswr** [comment]
It will become available in your CLI if you install the package globally via npm with `npm i -g swipl-wasm`.

If you don't want to install the package globally then you can run `npx -p swipl-wasm swipl-generate ./max.pl ./dist/max.ts` which will fetch the latest version of `swipl-wasm` from `npm` and then execute `swipl-generate`.

Either way; no need to clone the repo to achieve this.

**Comment by jeswr** [comment]
Note it is just implemented as a standard [npm bin](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#bin) entry.
