### ISSUE TITLE
Question: How to properly destroy `SWIPL`

### ISSUE THREAD

**Issue by jeswr** [SWI-Prolog/npm-swipl-wasm#23]
As observed in https://github.com/rla/npm-swipl-wasm/issues/22 calling `SWIPL` makes modifications in the global scope such as adding event listeners to the global process.

This means that there probably should also be some `.destroy()` or `.close()` function that should be used when we have finished using a given instantiation of `SWIPL` in order to clean-up such listeners and avoid memory leakage in long-running processes.

**Comment by jeswr** [comment]
It looks like the answer is that we need to add another build flag to provide such functionality (https://emscripten.org/docs/api_reference/emscripten.h.html?highlight=exit#c.emscripten_force_exit)

**Comment by jeswr** [comment]
Also just to note I have done some profiling with the following script

```ts
async function main() {
  for (let i = 0; i < 1000; i++) {
    if (i % 50 === 0) {
      console.log(i, process.memoryUsage().heapUsed / 1000000, 'MB')
    }
    await SWIPL({ print: () => {}, printErr: () => {} })
  }
}

main();
```

and the memory leakage is nontrivial (~0.5-1MB seems to be leaked per instantiation); the process dies before I can make 1000 calls

```
0 120.533344 MB
(node:11537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11537) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
50 118.26012 MB
100 141.230904 MB
150 161.35028 MB
200 184.055728 MB
250 205.562912 MB
300 225.89072 MB
350 248.516888 MB
400 270.084664 MB
450 290.446328 MB
500 313.003728 MB
550 334.532904 MB
600 354.97716 MB
650 377.570224 MB
700 399.117088 MB
750 419.376104 MB
800 442.1882 MB
Killed
```

**Comment by jeswr** [comment]
The cause is https://github.com/emscripten-core/emscripten/issues/18723 - removing those event listeners from the bundle result in no change in process usage after several thousand instantiations of `SWIPL`

**Comment by Madd0g** [comment]
I'm trying to evaluate a few hundred little prolog programs, I tried creating new instances of Swipl for each one and it quickly runs out of memory with this error:

```
failed to asynchronously prepare wasm: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
Aborted(RangeError: WebAssembly.instantiate(): Out of memory: wasm memory)
```

I tried using a single instance of Swipl and write the new file and re-consult before querying, but that didn't work at all and I kept getting errors from a previous file:

```
mod.FS.writeFile('file.pl', code);
mod.prolog.query('consult("file.pl").');

// gives errors from previous file content, so consult doesn't overwrite?
mod.prolog.query( .. new query ..); 
```

any advice?

**Comment by JanWielemaker** [comment]
Please use the SWI-Prolog Discourse forum for help.    Reconsulting should work, except for dynamic clauses.      A safe way is to use `in_temporary_module/3`.   It is a bit of a fragile predicate though, so read the docs carefully.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/using-the-wasm-version/6379/1

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/firebase-functions-swi-prolog-wasm-node-memory-build-up-issue/6435/2

**Comment by jeswr** [comment]
@JanWielemaker the issue is caused by the solved upstream bug https://github.com/emscripten-core/emscripten/issues/18723.

We just need to update the version of emscripten we use here.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/firebase-functions-swi-prolog-wasm-node-memory-build-up-issue/6435/4
