### ISSUE TITLE
Audit failed, problems with node-static

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [SWI-Prolog/npm-swipl-wasm#431]
He was using:
```
$ node -v
v20.10.0
```
Now it shows me after npm ci:
```
npm ci
npm WARN deprecated read-pkg-up@11.0.0: Renamed to read-package-up

added 798 packages, and audited 1062 packages in 22s

194 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 low, 1 moderate, 1 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```
Can I ignore?

**Comment by Jean-Luc-Picard-2021** [comment]
```
# npm audit report
```
Gives me this result:
```
# npm audit report

minimist  <=0.2.3
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-vh95-rmgr-6w4m
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/optimist/node_modules/minimist
  optimist  >=0.6.0
  Depends on vulnerable versions of minimist
  node_modules/optimist

node-static  *
Severity: high
Denial of Service in node-static - https://github.com/advisories/GHSA-8r4g-cg4m-x23c
node-static and @nubosoftware/node-static vulnerable to Directory Traversal - https://github.com/advisories/GHSA-5g97-whc9-8g7j
No fix available
node_modules/node-static

3 vulnerabilities (1 high, 2 critical)
```

**Comment by jeswr** [comment]
These only affect dev dependencies; not dependencies that we use in the packaged version of this tool, see:
```
$ npm audit --omit=dev
found 0 vulnerabilities
```

**Comment by Jean-Luc-Picard-2021** [comment]
But your npm-swipl-wasm does not provide swipl.js, so that you can do:
```
node swipl.js <Prolog Text> <Argument1> .. <Argumentn>
```

**Comment by jeswr** [comment]
The `swipl.js` referenced in that thread is included in the `swipl-wasm` package; it can be found in `/dist/swipl/swipl.js`.

**Comment by jeswr** [comment]
Note that if your goal is to use swipl in javascript then I would just refer to https://github.com/SWI-Prolog/npm-swipl-wasm?tab=readme-ov-file#swipl-wasm for the best ways to use this package.

**Comment by Jean-Luc-Picard-2021** [comment]
The dist directory doesn't show /dist/swipl/swipl.js if I do:
```
npm i swipl-wasm
```
swipl.js is not contained in the above distro:

**Comment by Jean-Luc-Picard-2021** [comment]
What you pointed at must be another swipl.js. I cannot use it in this form:
```
node swipl.js <Prolog Text> <Argument1> .. <Argumentn>
```
It does nothing:
```
$ cat > foo.p
:- write(hello), nl.
$ node ./swipl.js foo.p
```
It just returns to the shell. But my expectation was that it prints hello.

Maybe a node path or invocation problem?

**Comment by Jean-Luc-Picard-2021** [comment]
Concerning batch testing, without building wasm, but with downloading
an NPM package, you told me I should look here:

https://www.npmjs.com/package/swipl-wasm

But there is no `swipl.js` example listed. So I have absolutely
no clue what I need to do for batch testing.

Also the documentation doesn't reflect newest node, so its 
vary hard to follow, because most of the examples don't work anymore.

See also this other defect:

**Comment by jeswr** [comment]
> But there is no swipl.js use case listed, which is what I am looking for. So
I have absolutely no clue what I need to do for batch testing.

There is `swipl.js` use case listed because you shouldn't be needing to use that file directly. https://www.npmjs.com/package/swipl-wasm provides an abstraction on top of that file which bundles everything you need together and exports the `SWIPL` function which should be able to do everything you need and is described in the [getting started section of the readme](https://github.com/SWI-Prolog/npm-swipl-wasm/tree/master?tab=readme-ov-file#quickly-getting-started).

If you need to be loading a full prolog file rather than using basic functions described in that section of the readme, then your input to that `SWIPL` function probably needs to look something like https://github.com/eyereasoner/eye-js/blob/1ebd963d3c72d672ebefc2cca4c1ef784b659b80/lib/transformers.ts#L23-L25 or https://github.com/eyereasoner/eye-js/blame/54138910829146f97fd5407609430e2af64a13ad/lib/transformers.ts#L16-L39. Indeed it would be great to have documentation for this in the README, and PRs are happily accepted :)

#433 is a PR to update the readme, not an issue. You can see the readme updates in https://github.com/SWI-Prolog/npm-swipl-wasm/pull/433/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5.

**Comment by jeswr** [comment]
I'm not sure if the `swipl.js` generated there for testing is particularly different from the one used in this package. I would imagine not, but I'll let @JanWielemaker confirm.

In this package we create `../build.wasm/src/swipl.js` in [this dockerfile](https://github.com/SWI-Prolog/npm-swipl-wasm/blob/571a531ebd2b5b53bfbe901f69e121767c56317a/docker/Dockerfile#L42-L50) and then copy the `swipl.js` into `dist/swipl/swipl.js` using [this command](https://github.com/SWI-Prolog/npm-swipl-wasm/blob/571a531ebd2b5b53bfbe901f69e121767c56317a/package.json#L56). You will _not_ see this file in the GitHub repo as it is an artefact of the build process and so [.gitignored](https://github.com/SWI-Prolog/npm-swipl-wasm/blob/571a531ebd2b5b53bfbe901f69e121767c56317a/.gitignore#L2). It is available in the `dist/swipl/swipl.js` directory of the `swipl-wasm` package (you can visually navigate the folders in that package [here](https://www.npmjs.com/package/swipl-wasm?activeTab=code)).

>  I described what swipl.js does when I wrote:

The reason I pointed to [this link](https://github.com/eyereasoner/eye-js/blame/54138910829146f97fd5407609430e2af64a13ad/lib/transformers.ts#L16-L39) was to demonstrate how you could write a JS script to achieve what you're after using the abstractions exported by the `swipl-wasm` package. In particular you should be able to achieve what you've written by doing the following (there could be bugs, I don't have time to test the code right now) 

```ts
import SWIPL from "swipl-wasm"

/**
 * Executes a query
 * @param Module The module to execute the query on
 * @param name The name of the query function
 * @param args The arguments of the query function
 * @returns The result of the query
 */
export function query(Module: SWIPLModule, name: string, args: string[] | string) {
  const queryString = `${name}(${
    /* istanbul ignore next */
    typeof args === 'string'
      ? `"${args}"`
      : `[${args.map((arg) => `'${arg}'`).join(', ')}]`
  }).`;
  return Module.prolog.query(queryString);
}

export function queryOnce(Module: SWIPLModule, name: string, args: string[] | string) {
  return query(Module, name, args).once();
}

async function main() {
   const Module = await SWIPL();
   Module.FS.writeFile('example.pl', strToBuffer(/* prolog string */ ));
   queryOnce(Module, 'consult', 'eye.pl');
     queryOnce(Module, 'main', ['<Argument1>', ..., '<ArgumentN>']);
}
```

---

I hope that clarifies any confusion in my above responses.
