### ISSUE TITLE
Get rights correct

### ISSUE THREAD

**Issue by JanWielemaker** [SWI-Prolog/npm-swipl-wasm#45]
After moving, which rights do I have to give you, @jeswr ?   You now have `write`.   Seems the only other option (that makes sense) is Admin.    Is that what is required?

**Comment by jeswr** [comment]
>  Is that what is required?

Yes (needed to edit branch protections so automerges don't break things - and add `GH_TOKENS`)

**Comment by jeswr** [comment]
Closing as I seem to now have the necessary permissions :)
