### ISSUE TITLE
Should swipl-bundle.js be separately released as asset

### ISSUE THREAD

**Issue by xpxaxsxi** [SWI-Prolog/npm-swipl-wasm#718]
I ran the examples here [https://wasm.swi-prolog.org/wasm/](https://wasm.swi-prolog.org/wasm/), and then downloaded locally the Tau-Prolog app,  Then I http served locally the TP app, and it worked. 
Then  I realised that now 2024 August the latest swipl-bundle.js is served only as a npm package, isn't this too much to ask a interested Prolog user to get swipl-bundle.js by (in Windows): installing fnm, installing node, creating npm project and finally getting swipl-bundle.js  with npm i swipl-wasm

**Comment by xpxaxsxi** [comment]
Sorry I red the README more carefully and figured out that it is released here [https://swi-prolog.github.io/npm-swipl-wasm/3/3/0/index.js](https://swi-prolog.github.io/npm-swipl-wasm/3/3/0/index.js)

**Comment by jeswr** [comment]
FWIW npm also lets you access the distributed files in the code tab on their website https://www.npmjs.com/package/swipl-wasm?activeTab=code
